# -*- coding: utf-8 -*-
"""
core/contracts.py — Platform-Wide Domain Contracts, Types, and Protocols
=========================================================================

THIS IS THE SINGLE SOURCE OF TRUTH for all domain types used across the
pairs trading platform. All other modules should import types from here.

Design principles:
- All public types are dataclasses or enums (never bare dicts or tuples)
- All validation pipelines produce typed results with explicit rejection reasons
- All pair/spread states are tracked via a formal state machine (PairLifecycleState)
- All protocols define the minimal interface a component must satisfy
- No implicit global state; everything flows through typed contracts

Pair Lifecycle:
  CANDIDATE → VALIDATED → ACTIVE → SUSPENDED → RETIRED
      ↕            ↕           ↕
   REJECTED    PAUSED      BROKEN

"""

from __future__ import annotations

import enum
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional, Protocol, Sequence, Tuple, runtime_checkable

import numpy as np
import pandas as pd


# ══════════════════════════════════════════════════════════════════
# 1. ENUMERATIONS
# ══════════════════════════════════════════════════════════════════

class PairLifecycleState(str, enum.Enum):
    """Canonical states for a pair/spread relationship.

    State machine transitions:
        CANDIDATE  → VALIDATED (passed all statistical + economic tests)
        CANDIDATE  → REJECTED  (failed validation; rejection_reasons populated)
        VALIDATED  → ACTIVE    (allocated capital, signals live)
        VALIDATED  → PAUSED    (monitoring but not trading; e.g. low liquidity)
        ACTIVE     → SUSPENDED (temporarily halted; e.g. corporate action, regime)
        ACTIVE     → BROKEN    (relationship broken; structural break detected)
        ACTIVE     → RETIRED   (gracefully exited; relationship still valid but deprioritized)
        SUSPENDED  → ACTIVE    (re-enabled after resolution)
        SUSPENDED  → BROKEN    (break confirmed during suspension)
        BROKEN     → RETIRED   (permanent retirement after confirmed break)
        BROKEN     → CANDIDATE (re-evaluation after major reset; rare)
    """
    CANDIDATE  = "CANDIDATE"   # Generated by universe screen, not yet validated
    VALIDATED  = "VALIDATED"   # Passed all statistical + economic tests
    ACTIVE     = "ACTIVE"      # Live: capital allocated, signals generated
    PAUSED     = "PAUSED"      # Monitored but not traded (e.g., low liquidity window)
    SUSPENDED  = "SUSPENDED"   # Temporarily halted (regime, event, circuit-breaker)
    BROKEN     = "BROKEN"      # Structural break detected; relationship invalidated
    RETIRED    = "RETIRED"     # Gracefully exited; no longer in active universe
    REJECTED   = "REJECTED"    # Failed validation; logged with rejection_reasons


class ValidationResult(str, enum.Enum):
    """Outcome of pair validation pipeline."""
    PASS     = "PASS"     # All tests passed; pair is tradable
    FAIL     = "FAIL"     # One or more hard tests failed; not tradable
    WARN     = "WARN"     # Passed hard tests but flagged by soft tests; trade with reduced size
    SKIP     = "SKIP"     # Insufficient data or other pre-condition not met


class RegimeLabel(str, enum.Enum):
    """Canonical regime labels used throughout the platform.

    These labels are the contract between the regime classifier
    and every downstream consumer (signal engine, risk engine, etc.).
    """
    MEAN_REVERTING = "MEAN_REVERTING"  # Low vol, tight range, signals work well
    TRENDING       = "TRENDING"        # Directional momentum; mean reversion hazardous
    HIGH_VOL       = "HIGH_VOL"        # Elevated volatility; reduce size
    CRISIS         = "CRISIS"          # Extreme stress; consider halting new entries
    BROKEN         = "BROKEN"          # Pair-level structural break detected
    UNKNOWN        = "UNKNOWN"         # Insufficient data or classification failed


class SignalDirection(str, enum.Enum):
    """Direction of a trading signal."""
    LONG_SPREAD  = "LONG_SPREAD"   # Buy X, Sell Y (spread below equilibrium)
    SHORT_SPREAD = "SHORT_SPREAD"  # Sell X, Buy Y (spread above equilibrium)
    FLAT         = "FLAT"          # No signal or exit signal
    EXIT         = "EXIT"          # Close existing position


class SpreadModel(str, enum.Enum):
    """Spread construction method."""
    STATIC_OLS   = "STATIC_OLS"    # OLS hedge ratio on full training window
    ROLLING_OLS  = "ROLLING_OLS"   # Rolling window OLS
    KALMAN       = "KALMAN"        # Kalman filter (time-varying hedge ratio)
    TOTAL_RETURN = "TOTAL_RETURN"  # Price ratio (log-price difference)
    FACTOR_NEUTRAL = "FACTOR_NEUTRAL"  # Residual after factor removal


class HedgeRatioMethod(str, enum.Enum):
    """Method for estimating the hedge ratio."""
    OLS          = "OLS"         # Ordinary Least Squares
    TLS          = "TLS"         # Total Least Squares (symmetric)
    ROLLING      = "ROLLING"     # Rolling window OLS
    KALMAN       = "KALMAN"      # Kalman filter
    JOHANSEN     = "JOHANSEN"    # Johansen cointegration eigenvector


class BreakType(str, enum.Enum):
    """Type of structural break detected."""
    CUSUM        = "CUSUM"        # CUSUM test on residuals
    CHOW         = "CHOW"         # Chow test (known breakpoint)
    CHANGE_POINT = "CHANGE_POINT" # Algorithmic change-point detection
    RESIDUAL_VAR = "RESIDUAL_VAR" # Residual variance explosion
    CORRELATION  = "CORRELATION"  # Rolling correlation collapse
    HALF_LIFE    = "HALF_LIFE"    # Half-life deterioration beyond threshold


class RiskBreachType(str, enum.Enum):
    """Types of risk limit breaches."""
    MAX_DRAWDOWN        = "MAX_DRAWDOWN"
    MAX_GROSS_EXPOSURE  = "MAX_GROSS_EXPOSURE"
    MAX_NET_EXPOSURE    = "MAX_NET_EXPOSURE"
    PAIR_CONCENTRATION  = "PAIR_CONCENTRATION"
    CLUSTER_CONCENTRATION = "CLUSTER_CONCENTRATION"
    VIX_THRESHOLD       = "VIX_THRESHOLD"
    DAILY_LOSS          = "DAILY_LOSS"
    KILL_SWITCH         = "KILL_SWITCH"


class AgentStatus(str, enum.Enum):
    """Status of an agent task execution."""
    PENDING   = "PENDING"
    RUNNING   = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED    = "FAILED"
    BLOCKED   = "BLOCKED"   # Blocked by risk or approval gate
    CANCELLED = "CANCELLED"


class TradeLifecycleState(str, enum.Enum):
    """Extended lifecycle states for active spread management.

    More granular than PairLifecycleState; used by the lifecycle state machine.
    Each state has explicit allowed actions, forbidden actions, and transition triggers.

    Typical forward path:
        WATCHLIST → SETUP_FORMING → ENTRY_READY → PENDING_ENTRY → ACTIVE
                                                                     ↓
        COOLDOWN ←─ EXIT_READY ←─ REDUCING ←─ ACTIVE ──→ SCALING_IN
           ↓
        WATCHLIST (re-entry) or SUSPENDED / RETIRED
    """
    NOT_ELIGIBLE  = "NOT_ELIGIBLE"   # Relationship invalid / blocked
    WATCHLIST     = "WATCHLIST"      # Validated, monitoring, no active signal
    SETUP_FORMING = "SETUP_FORMING"  # Signal conditions beginning to emerge
    ENTRY_READY   = "ENTRY_READY"    # Signal qualified, may be proposed to risk/portfolio
    PENDING_ENTRY = "PENDING_ENTRY"  # Intent approved, awaiting fill confirmation
    ACTIVE        = "ACTIVE"         # Position live, monitoring continues
    SCALING_IN    = "SCALING_IN"     # Scale-in leg in progress
    REDUCING      = "REDUCING"       # Partial exit in progress
    EXIT_READY    = "EXIT_READY"     # Should be closed based on signal/risk/lifecycle
    PENDING_EXIT  = "PENDING_EXIT"   # Exit approved, awaiting fill confirmation
    COOLDOWN      = "COOLDOWN"       # Temporary no-reentry after exit/stop
    SUSPENDED     = "SUSPENDED"      # Temporarily blocked (regime, event, risk)
    RETIRED       = "RETIRED"        # No longer traded until revalidated


class ExitReason(str, enum.Enum):
    """Structured exit reasons. Multiple reasons may apply simultaneously.

    Used in ExitIntent and recorded in trade audit logs.
    """
    # ── Mean-reversion completion ─────────────────────────────────
    MEAN_REVERSION_COMPLETE = "MEAN_REVERSION_COMPLETE"
    TARGET_REACHED          = "TARGET_REACHED"
    PARTIAL_CONVERGENCE     = "PARTIAL_CONVERGENCE"
    DIMINISHING_EDGE        = "DIMINISHING_EDGE"
    # ── Time-based ───────────────────────────────────────────────
    TIME_STOP    = "TIME_STOP"
    SIGNAL_DECAY = "SIGNAL_DECAY"
    STALE_TRADE  = "STALE_TRADE"
    # ── Risk-based ───────────────────────────────────────────────
    ADVERSE_EXCURSION_STOP = "ADVERSE_EXCURSION_STOP"
    SPREAD_STOP            = "SPREAD_STOP"
    VOLATILITY_SPIKE       = "VOLATILITY_SPIKE"
    INSTABILITY_TRIGGERED  = "INSTABILITY_TRIGGERED"
    BREAK_RISK             = "BREAK_RISK"
    # ── Regime-based ─────────────────────────────────────────────
    REGIME_FLIP         = "REGIME_FLIP"
    STRUCTURAL_BREAK    = "STRUCTURAL_BREAK"
    NOISY_REGIME        = "NOISY_REGIME"
    EVENT_CONTAMINATION = "EVENT_CONTAMINATION"
    # ── Opportunity-cost / portfolio ─────────────────────────────
    CAPITAL_RECYCLING    = "CAPITAL_RECYCLING"
    PORTFOLIO_CONSTRAINT = "PORTFOLIO_CONSTRAINT"
    # ── Partial-exit / reduction ─────────────────────────────────
    STAGED_PROFIT_TAKING = "STAGED_PROFIT_TAKING"
    REGIME_WEAKENING     = "REGIME_WEAKENING"
    CONFIDENCE_COLLAPSE  = "CONFIDENCE_COLLAPSE"
    # ── System ───────────────────────────────────────────────────
    MANUAL_EXIT = "MANUAL_EXIT"
    KILL_SWITCH = "KILL_SWITCH"


class BlockReason(str, enum.Enum):
    """Why an entry signal was blocked. Always populated when action = WATCH/BLOCK."""
    # ── Eligibility ──────────────────────────────────────────────
    VALIDATION_FAILED = "VALIDATION_FAILED"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    NOT_VALIDATED     = "NOT_VALIDATED"
    # ── Regime ───────────────────────────────────────────────────
    REGIME_INVALID        = "REGIME_INVALID"
    REGIME_TRENDING       = "REGIME_TRENDING"
    REGIME_CRISIS         = "REGIME_CRISIS"
    STRUCTURAL_BREAK_RISK = "STRUCTURAL_BREAK_RISK"
    # ── Signal quality ───────────────────────────────────────────
    LOW_QUALITY_SIGNAL   = "LOW_QUALITY_SIGNAL"
    LATE_DISLOCATION     = "LATE_DISLOCATION"
    SIGNAL_CONTAMINATED  = "SIGNAL_CONTAMINATED"
    DIVERGENCE_TOO_SMALL = "DIVERGENCE_TOO_SMALL"
    DIVERGENCE_TOO_LARGE = "DIVERGENCE_TOO_LARGE"
    # ── Lifecycle ────────────────────────────────────────────────
    COOLDOWN_ACTIVE  = "COOLDOWN_ACTIVE"
    SUSPENDED        = "SUSPENDED"
    RETIRED          = "RETIRED"
    # ── Risk / portfolio ─────────────────────────────────────────
    RISK_GATE           = "RISK_GATE"
    PORTFOLIO_FULL      = "PORTFOLIO_FULL"
    CONCENTRATION_LIMIT = "CONCENTRATION_LIMIT"
    VOLATILITY_CONFLICT = "VOLATILITY_CONFLICT"
    # ── Time ─────────────────────────────────────────────────────
    STALE_SIGNAL      = "STALE_SIGNAL"
    PENDING_EXECUTION = "PENDING_EXECUTION"
    # ── Other ────────────────────────────────────────────────────
    MANUAL_BLOCK = "MANUAL_BLOCK"


class IntentAction(str, enum.Enum):
    """Action proposed by a signal intent.

    Signals propose actions; portfolio/risk/execution layers decide.
    """
    WATCH   = "WATCH"    # Monitor; no action required
    ENTER   = "ENTER"    # Open new position
    ADD     = "ADD"      # Scale into existing position
    HOLD    = "HOLD"     # Maintain current position; no change
    REDUCE  = "REDUCE"   # Partial exit
    EXIT    = "EXIT"     # Full exit
    SUSPEND = "SUSPEND"  # Temporarily pause this spread
    RETIRE  = "RETIRE"   # Permanently deactivate until revalidated


class SignalQualityGrade(str, enum.Enum):
    """Holistic quality grade for a signal setup."""
    A_PLUS = "A+"   # Exceptional: all dimensions strong, clean regime
    A      = "A"    # Strong: most dimensions solid
    B      = "B"    # Acceptable: some weaknesses but tradable
    C      = "C"    # Marginal: notable weaknesses, reduced conviction
    D      = "D"    # Weak: significant concerns, approach with caution
    F      = "F"    # Skip: do not trade this setup


# ══════════════════════════════════════════════════════════════════
# 2. CORE DOMAIN OBJECTS
# ══════════════════════════════════════════════════════════════════

@dataclass(frozen=True)
class PairId:
    """Canonical, hashable pair identifier. sym_x < sym_y lexicographically."""
    sym_x: str
    sym_y: str

    def __post_init__(self):
        # Enforce canonical ordering to prevent (A,B) and (B,A) duplicates
        if self.sym_x > self.sym_y:
            orig_x = self.sym_x
            object.__setattr__(self, "sym_x", self.sym_y)
            object.__setattr__(self, "sym_y", orig_x)

    @property
    def label(self) -> str:
        return f"{self.sym_x}/{self.sym_y}"

    def __str__(self) -> str:
        return self.label

    def __contains__(self, symbol: str) -> bool:
        return symbol in (self.sym_x, self.sym_y)

    def as_tuple(self) -> tuple[str, str]:
        return (self.sym_x, self.sym_y)

    @classmethod
    def from_label(cls, label: str) -> "PairId":
        """Parse a 'SYM_X/SYM_Y' label. Auto-sorts for canonical order."""
        parts = label.split("/")
        if len(parts) != 2 or not all(parts):
            raise ValueError(f"Invalid PairId label: {label!r}. Expected 'SYM_X/SYM_Y'.")
        return cls(parts[0], parts[1])


@dataclass
class ValidationTest:
    """Result of a single validation test (e.g., ADF, half-life, correlation)."""
    name: str
    passed: bool
    is_hard: bool           # Hard fail = REJECT; soft fail = WARN
    value: float = np.nan   # Test statistic or metric value
    threshold: float = np.nan  # Threshold used for pass/fail
    message: str = ""       # Human-readable interpretation
    pvalue: float = np.nan  # p-value if applicable


@dataclass
class PairValidationReport:
    """
    Full validation report for a candidate pair.

    This is the authoritative record of WHY a pair was accepted, warned,
    or rejected. Every rejection reason is explicitly captured here.
    """
    pair_id: PairId
    result: ValidationResult
    timestamp: datetime = field(default_factory=datetime.utcnow)

    # Individual test results
    tests: list[ValidationTest] = field(default_factory=list)

    # Summary metrics (populated even on rejection for diagnostics)
    correlation: float = np.nan
    adf_pvalue: float = np.nan
    half_life_days: float = np.nan
    hurst_exponent: float = np.nan
    spread_vol: float = np.nan
    residual_vol: float = np.nan
    hedge_ratio: float = np.nan
    hedge_ratio_method: HedgeRatioMethod = HedgeRatioMethod.OLS
    cointegration_pvalue: float = np.nan
    rolling_stability: float = np.nan   # 0-1 score of hedge ratio stability

    # Rejection reasons (empty if PASS)
    rejection_reasons: list[str] = field(default_factory=list)
    # Warning reasons (advisory; trade with reduced size)
    warning_reasons: list[str] = field(default_factory=list)

    # Metadata
    train_start: Optional[datetime] = None
    train_end: Optional[datetime] = None
    n_obs: int = 0
    spread_model: SpreadModel = SpreadModel.STATIC_OLS

    @property
    def is_tradable(self) -> bool:
        return self.result in (ValidationResult.PASS, ValidationResult.WARN)

    @property
    def failed_hard_tests(self) -> list[ValidationTest]:
        return [t for t in self.tests if not t.passed and t.is_hard]

    @property
    def failed_soft_tests(self) -> list[ValidationTest]:
        return [t for t in self.tests if not t.passed and not t.is_hard]

    def to_dict(self) -> dict:
        return {
            "pair": self.pair_id.label,
            "result": self.result.value,
            "correlation": self.correlation,
            "adf_pvalue": self.adf_pvalue,
            "half_life_days": self.half_life_days,
            "hurst_exponent": self.hurst_exponent,
            "hedge_ratio": self.hedge_ratio,
            "cointegration_pvalue": self.cointegration_pvalue,
            "rolling_stability": self.rolling_stability,
            "n_obs": self.n_obs,
            "rejection_reasons": self.rejection_reasons,
            "warning_reasons": self.warning_reasons,
            "timestamp": self.timestamp.isoformat(),
        }


@dataclass
class SpreadDefinition:
    """
    Complete definition of a spread/residual series.

    Encapsulates how the spread is constructed, normalized, and interpreted.
    """
    pair_id: PairId
    model: SpreadModel
    hedge_ratio: float
    hedge_ratio_method: HedgeRatioMethod
    intercept: float = 0.0
    half_life_days: float = np.nan
    mean: float = 0.0
    std: float = 1.0

    # Rolling parameters (if model is ROLLING or KALMAN)
    window: int = 60
    kalman_observation_cov: float = 0.001
    kalman_transition_cov: float = 0.0001

    # Factor neutralization
    factor_names: list[str] = field(default_factory=list)
    factor_loadings: list[float] = field(default_factory=list)

    # Estimation metadata
    estimated_at: Optional[datetime] = None
    train_start: Optional[datetime] = None
    train_end: Optional[datetime] = None

    def compute_spread(
        self,
        price_x: pd.Series,
        price_y: pd.Series,
    ) -> pd.Series:
        """Compute the raw (un-normalized) spread series."""
        raw = price_x - self.hedge_ratio * price_y - self.intercept
        raw.name = f"spread_{self.pair_id.label}"
        return raw

    def compute_zscore(
        self,
        price_x: pd.Series,
        price_y: pd.Series,
        *,
        rolling_window: Optional[int] = None,
    ) -> pd.Series:
        """Compute the z-scored spread."""
        raw = self.compute_spread(price_x, price_y)
        if rolling_window and rolling_window > 0:
            mu = raw.rolling(rolling_window).mean()
            sigma = raw.rolling(rolling_window).std()
        else:
            mu = self.mean
            sigma = self.std
        z = (raw - mu) / sigma.clip(lower=1e-8) if isinstance(sigma, pd.Series) else (raw - mu) / max(sigma, 1e-8)
        z.name = f"z_{self.pair_id.label}"
        return z


@dataclass
class RegimeState:
    """Current regime classification for a pair or market."""
    label: RegimeLabel
    confidence: float = 1.0          # 0-1 probability of this regime
    probabilities: dict[str, float] = field(default_factory=dict)
    features: dict[str, float] = field(default_factory=dict)
    transition_probability: float = 0.0  # Prob of regime change in next period
    classified_at: Optional[datetime] = None
    valid_until: Optional[datetime] = None

    @property
    def is_tradable(self) -> bool:
        """Is mean reversion likely to work in this regime?"""
        return self.label in (RegimeLabel.MEAN_REVERTING, RegimeLabel.UNKNOWN)

    @property
    def is_high_risk(self) -> bool:
        return self.label in (RegimeLabel.CRISIS, RegimeLabel.BROKEN)


@dataclass
class TradeSignal:
    """
    A typed trading signal. Produced by signal engines, consumed by
    execution/portfolio layers. Never acts as its own executor.
    """
    pair_id: PairId
    direction: SignalDirection
    z_score: float
    confidence: float = 1.0           # 0-1 signal confidence
    entry_z: float = np.nan           # Threshold that triggered entry
    exit_z: float = np.nan            # Target z for exit
    stop_z: float = np.nan            # Hard stop z-score
    half_life: float = np.nan         # Expected days to mean-revert
    regime: RegimeLabel = RegimeLabel.UNKNOWN
    features: dict[str, float] = field(default_factory=dict)
    generated_at: Optional[datetime] = None
    meta_label: Optional[float] = None  # ML meta-label (0=skip, 1=take)
    notes: str = ""

    @property
    def is_entry(self) -> bool:
        return self.direction in (SignalDirection.LONG_SPREAD, SignalDirection.SHORT_SPREAD)

    @property
    def is_exit(self) -> bool:
        return self.direction in (SignalDirection.EXIT, SignalDirection.FLAT)


@dataclass
class StructuralBreakResult:
    """Result of structural break / relationship stability test."""
    pair_id: PairId
    break_detected: bool
    break_type: Optional[BreakType] = None
    break_date: Optional[datetime] = None
    confidence: float = 0.0   # 0-1 probability of break
    test_statistic: float = np.nan
    pvalue: float = np.nan
    description: str = ""
    recommended_action: str = ""  # "SUSPEND", "RETIRE", "INVESTIGATE"


@dataclass
class RiskBreach:
    """A single risk limit breach event."""
    breach_type: RiskBreachType
    current_value: float
    limit_value: float
    severity: float             # 0-1 (1 = kill switch level)
    pair_id: Optional[PairId] = None  # None = portfolio-level breach
    description: str = ""
    detected_at: datetime = field(default_factory=datetime.utcnow)
    requires_action: bool = True

    @property
    def excess_pct(self) -> float:
        """How far over the limit, as a percentage."""
        if self.limit_value == 0:
            return float("inf")
        return (self.current_value - self.limit_value) / abs(self.limit_value) * 100


@dataclass
class ExperimentConfig:
    """Configuration for a research experiment (walk-forward, backtests, etc.)."""
    experiment_id: str
    description: str = ""
    pair_id: Optional[PairId] = None
    universe_name: str = ""
    train_start: Optional[datetime] = None
    train_end: Optional[datetime] = None
    test_start: Optional[datetime] = None
    test_end: Optional[datetime] = None
    params: dict = field(default_factory=dict)
    tags: list[str] = field(default_factory=list)
    created_at: datetime = field(default_factory=datetime.utcnow)
    random_seed: int = 42

    def to_dict(self) -> dict:
        d = {k: v for k, v in self.__dict__.items()}
        if self.pair_id:
            d["pair_id"] = self.pair_id.label
        for dt_key in ("train_start", "train_end", "test_start", "test_end", "created_at"):
            if d.get(dt_key):
                d[dt_key] = d[dt_key].isoformat()
        return d


@dataclass
class ExperimentResult:
    """Typed result of a research experiment."""
    experiment_id: str
    sharpe: float = np.nan
    sortino: float = np.nan
    calmar: float = np.nan
    annualized_return: float = np.nan
    max_drawdown: float = np.nan
    win_rate: float = np.nan
    n_trades: int = 0
    avg_holding_days: float = np.nan
    turnover: float = np.nan
    information_coefficient: float = np.nan
    metrics: dict = field(default_factory=dict)
    artifacts: dict = field(default_factory=dict)  # paths to saved files
    completed_at: datetime = field(default_factory=datetime.utcnow)
    notes: str = ""


# ══════════════════════════════════════════════════════════════════
# 3. AGENT CONTRACTS
# ══════════════════════════════════════════════════════════════════

@dataclass
class AgentTask:
    """
    Typed task contract for any agent.

    Agents receive AgentTask objects and produce AgentResult objects.
    No agent should accept or produce bare dicts.
    """
    task_id: str
    agent_name: str
    task_type: str              # e.g. "validate_pair", "classify_regime"
    payload: dict               # Task-specific parameters (agent-defined schema)
    priority: int = 5           # 1=highest, 10=lowest
    requires_approval: bool = False
    correlation_id: str = ""    # For tracing chains of tasks
    created_at: datetime = field(default_factory=datetime.utcnow)
    deadline: Optional[datetime] = None
    metadata: dict = field(default_factory=dict)


@dataclass
class AgentResult:
    """Typed result from an agent task execution."""
    task_id: str
    agent_name: str
    status: AgentStatus
    output: dict = field(default_factory=dict)  # Agent-defined structured output
    error: str = ""
    warnings: list[str] = field(default_factory=list)
    audit_trail: list[str] = field(default_factory=list)  # Key decision steps
    completed_at: datetime = field(default_factory=datetime.utcnow)
    duration_ms: float = 0.0
    requires_human_review: bool = False

    @property
    def succeeded(self) -> bool:
        return self.status == AgentStatus.COMPLETED

    def log(self, step: str) -> None:
        """Add an auditable step to the trail."""
        self.audit_trail.append(f"{datetime.utcnow().isoformat()} | {step}")


# ══════════════════════════════════════════════════════════════════
# 4. ML CONTRACTS
# ══════════════════════════════════════════════════════════════════

@dataclass
class ModelMetadata:
    """Metadata for a trained ML model."""
    model_id: str
    model_type: str            # e.g. "GBM", "LogisticRegression"
    task: str                  # e.g. "regime_classification", "reversion_probability"
    features: list[str] = field(default_factory=list)
    target: str = ""
    train_start: Optional[datetime] = None
    train_end: Optional[datetime] = None
    validation_score: float = np.nan
    oos_score: float = np.nan
    n_train_samples: int = 0
    n_features: int = 0
    is_champion: bool = False
    created_at: datetime = field(default_factory=datetime.utcnow)
    params: dict = field(default_factory=dict)
    metrics: dict = field(default_factory=dict)
    artifact_path: str = ""


@dataclass
class ModelPrediction:
    """Typed prediction output from a model."""
    model_id: str
    prediction: float         # Primary prediction (probability or regression value)
    confidence: float = 1.0   # Calibrated confidence
    lower_bound: float = np.nan
    upper_bound: float = np.nan
    predicted_at: datetime = field(default_factory=datetime.utcnow)
    feature_contributions: dict[str, float] = field(default_factory=dict)
    is_reliable: bool = True   # False if outside training distribution (drift flag)
    notes: str = ""


@dataclass
class DatasetSpec:
    """Specification for building a ML training dataset."""
    dataset_id: str
    task: str
    feature_names: list[str]
    target_name: str
    train_start: datetime
    train_end: datetime
    embargo_days: int = 5       # Gap between train and test to prevent leakage
    purge_days: int = 10        # Purge overlapping train samples near test boundary
    min_samples: int = 100
    max_lookahead_days: int = 0  # Must be 0 for production; > 0 only for research flags
    created_at: datetime = field(default_factory=datetime.utcnow)
    notes: str = ""

    def validate(self) -> list[str]:
        """Return list of validation errors (empty = valid)."""
        errors = []
        if self.max_lookahead_days > 0:
            errors.append(
                f"LEAKAGE WARNING: max_lookahead_days={self.max_lookahead_days}. "
                "Set to 0 for production-grade research."
            )
        if self.embargo_days < 1:
            errors.append("embargo_days should be >= 1 for time-series data.")
        if self.train_end <= self.train_start:
            errors.append("train_end must be after train_start.")
        return errors


# ══════════════════════════════════════════════════════════════════
# 5. PROTOCOLS (INTERFACES)
# ══════════════════════════════════════════════════════════════════

@runtime_checkable
class PairValidatorProtocol(Protocol):
    """Interface that every pair validator must satisfy."""

    def validate(
        self,
        pair_id: PairId,
        prices: pd.DataFrame,
        *,
        train_end: Optional[datetime] = None,
    ) -> PairValidationReport:
        """Run all validation tests and return a structured report."""
        ...


@runtime_checkable
class SpreadConstructorProtocol(Protocol):
    """Interface for all spread construction methods."""

    def fit(
        self,
        price_x: pd.Series,
        price_y: pd.Series,
        *,
        train_end: Optional[datetime] = None,
    ) -> SpreadDefinition:
        """Estimate hedge ratio and spread parameters from training data."""
        ...

    def transform(
        self,
        price_x: pd.Series,
        price_y: pd.Series,
        defn: SpreadDefinition,
    ) -> pd.Series:
        """Apply an existing SpreadDefinition to produce z-scores."""
        ...


@runtime_checkable
class RegimeClassifierProtocol(Protocol):
    """Interface for regime classification."""

    def classify(
        self,
        features: pd.DataFrame,
    ) -> RegimeState:
        """Classify the current regime from feature data."""
        ...


@runtime_checkable
class SignalEngineProtocol(Protocol):
    """Interface for signal engines."""

    def generate(
        self,
        pair_id: PairId,
        spread_def: SpreadDefinition,
        prices: pd.DataFrame,
        regime: RegimeState,
    ) -> TradeSignal:
        """Generate a trading signal for a pair."""
        ...


@runtime_checkable
class BacktesterProtocol(Protocol):
    """Minimal interface for any backtester."""

    def run(
        self,
        prices: pd.DataFrame,
        spread_def: SpreadDefinition,
        params: dict,
    ) -> ExperimentResult:
        """Run a backtest and return results."""
        ...


@runtime_checkable
class AgentProtocol(Protocol):
    """Interface every agent must satisfy."""

    @property
    def name(self) -> str:
        """Unique agent identifier."""
        ...

    @property
    def permitted_task_types(self) -> list[str]:
        """Task types this agent is authorized to handle."""
        ...

    def execute(self, task: AgentTask) -> AgentResult:
        """Execute a task and return a structured, auditable result."""
        ...


# ══════════════════════════════════════════════════════════════════
# 6. PORTFOLIO CONTRACTS
# ══════════════════════════════════════════════════════════════════

@dataclass
class SpreadAllocation:
    """Capital allocation decision for a single spread."""
    pair_id: PairId
    target_notional: float
    target_weight: float         # Fraction of total capital
    risk_contribution: float     # Fraction of total portfolio risk
    conviction: float            # Signal strength 0-1
    leverage: float = 1.0
    direction: SignalDirection = SignalDirection.FLAT
    approved: bool = True
    rejection_reason: str = ""


@dataclass
class PortfolioState:
    """Complete portfolio state snapshot."""
    timestamp: datetime
    total_capital: float
    gross_exposure: float
    net_exposure: float
    n_active_pairs: int
    allocations: list[SpreadAllocation] = field(default_factory=list)
    regime: RegimeLabel = RegimeLabel.UNKNOWN
    drawdown_from_peak: float = 0.0
    daily_pnl: float = 0.0
    realized_vol: float = np.nan

    @property
    def gross_leverage(self) -> float:
        if self.total_capital <= 0:
            return 0.0
        return self.gross_exposure / self.total_capital

    @property
    def net_leverage(self) -> float:
        if self.total_capital <= 0:
            return 0.0
        return abs(self.net_exposure) / self.total_capital


# ══════════════════════════════════════════════════════════════════
# 7. CONSTANTS AND DEFAULTS
# ══════════════════════════════════════════════════════════════════

class ValidationThresholds:
    """Default validation thresholds. Override via config."""
    MIN_CORRELATION: float = 0.60
    MAX_ADF_PVALUE: float = 0.10
    MAX_COINT_PVALUE: float = 0.10
    MIN_HALF_LIFE_DAYS: float = 2.0
    MAX_HALF_LIFE_DAYS: float = 120.0
    MIN_HURST_EXPONENT: float = 0.0     # < 0.5 = mean-reverting
    MAX_HURST_EXPONENT: float = 0.45    # Hard threshold for mean-reversion quality
    MIN_ROLLING_STABILITY: float = 0.60  # Hedge ratio rolling stability score
    MIN_OBS: int = 252                  # Minimum trading days for validation (R-002/ADR-007: 1 full trading year)
    MAX_SPREAD_VOL_RATIO: float = 3.0   # Max spread vol vs historical average


class PlatformConstants:
    """Platform-wide constants."""
    TRADING_DAYS_PER_YEAR: int = 252
    MIN_LIQUIDITY_ADV_USD: float = 1_000_000.0
    MAX_PAIRS_IN_UNIVERSE: int = 500
    DEFAULT_Z_ENTRY: float = 2.0
    DEFAULT_Z_EXIT: float = 0.5
    DEFAULT_Z_STOP: float = 4.0
    DEFAULT_LOOKBACK_DAYS: int = 252
    EMBARGO_DAYS: int = 5
    PURGE_DAYS: int = 10


# ── Production Safety Contracts ──────────────────────────────────

@runtime_checkable
class StateProvider(Protocol):
    """
    Abstract state storage — decouples core logic from Streamlit.

    Implementations:
    - StreamlitStateProvider (root/ only)
    - InMemoryStateProvider (tests, CLI, API)
    - DictStateProvider (minimal fallback)
    """
    def get(self, key: str, default: Any = None) -> Any: ...
    def set(self, key: str, value: Any) -> None: ...
    def has(self, key: str) -> bool: ...


class InMemoryStateProvider:
    """Thread-safe in-memory state for CLI, tests, and API."""
    def __init__(self) -> None:
        self._store: Dict[str, Any] = {}
    def get(self, key: str, default: Any = None) -> Any:
        return self._store.get(key, default)
    def set(self, key: str, value: Any) -> None:
        self._store[key] = value
    def has(self, key: str) -> bool:
        return key in self._store


@dataclass(frozen=True)
class EngineContract:
    """
    Every quant engine must declare its contract.

    This enables governance: classify engines as PRODUCTION vs RESEARCH,
    define failure modes, and track economic value.
    """
    name: str
    purpose: str
    inputs: Dict[str, str]
    outputs: Dict[str, str]
    failure_mode: str              # What happens on error
    fallback: str                  # Degraded behavior
    owner: str                     # Module path
    consumers: Tuple[str, ...]     # Who uses this output
    economic_value: str            # "alpha" / "risk" / "governance" / "research"
    classification: str            # "PRODUCTION" / "RESEARCH" / "EXPERIMENTAL"


@dataclass
class ActionThrottleConfig:
    """
    Cool-down and rate limits for agent feedback actions.

    Prevents cascading actions in volatile markets.
    """
    cool_down_seconds: Dict[str, int] = field(default_factory=lambda: {
        "KILL_SWITCH": 3600,       # 1 hour
        "DELEVERAGE": 1800,        # 30 min
        "FORCE_EXIT": 300,         # 5 min per pair
        "BLOCK_ENTRY": 600,        # 10 min
        "ADJUST_THRESHOLD": 1800,  # 30 min
        "RETRAIN_MODEL": 86400,    # 1 per day
        "OPTIMIZE_PARAMS": 86400,  # 1 per day
        "UPDATE_CONFIG": 3600,     # 1 per hour
    })
    max_actions_per_cycle: int = 10
    max_emergency_actions_per_day: int = 5


__all__ = [
    # Enums
    "PairLifecycleState", "TradeLifecycleState", "ValidationResult", "RegimeLabel",
    "SignalDirection", "SpreadModel", "HedgeRatioMethod",
    "BreakType", "RiskBreachType", "AgentStatus",
    "ExitReason", "BlockReason", "IntentAction", "SignalQualityGrade",
    # Domain objects
    "PairId", "ValidationTest", "PairValidationReport",
    "SpreadDefinition", "RegimeState", "TradeSignal",
    "StructuralBreakResult", "RiskBreach",
    "ExperimentConfig", "ExperimentResult",
    # Agent contracts
    "AgentTask", "AgentResult",
    # ML contracts
    "ModelMetadata", "ModelPrediction", "DatasetSpec",
    # Portfolio contracts
    "SpreadAllocation", "PortfolioState",
    # Protocols
    "PairValidatorProtocol", "SpreadConstructorProtocol",
    "RegimeClassifierProtocol", "SignalEngineProtocol",
    "BacktesterProtocol", "AgentProtocol",
    # Constants
    "ValidationThresholds", "PlatformConstants",
    # Production Safety
    "StateProvider", "InMemoryStateProvider",
    "EngineContract", "ActionThrottleConfig",
]
